name: Claude Auto Fix

on:
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed

jobs:
  claude-review:
    # Optional: Filter by PR author
    # if: |
    #   github.event.pull_request.user.login == 'external-contributor' ||
    #   github.event.pull_request.user.login == 'new-developer' ||
    #   github.event.pull_request.author_association == 'FIRST_TIME_CONTRIBUTOR'

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read # Required for Claude to read CI results on PRs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run Claude Code Review
        id: claude-review
        uses: anthropics/claude-code-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          additional_permissions: |
            actions: read
            contents: write
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number }}

            Los tests han fallado en el workflow de GitHub Actions.

            Por favor:
            1. Revisa los errores de los tests en el directorio Tests/
            2. Analiza qué está causando los fallos
            3. Corrige el código para que los tests pasen
            4. Asegúrate de que todos los tests se ejecuten correctamente

            Branch: ${{ steps.get-test-info.outputs.branch }}
            Workflow Run ID: ${{ steps.get-test-info.outputs.run_id }}

            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.
            Use `git add, git commit and git push` to push changes to github with the fixes

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh *),Bash(git *)" --dangerously-skip-permissions'

