name: Hello World

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
    - name: Print Hello World
      run: echo "Hello World"

    - name: Print additional message
      run: |
        echo "¡Bienvenido a GitHub Actions!"
        echo "Este es un workflow de ejemplo"
